require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
end

desc 'Run demo'
task :run do
  sh 'ruby main.rb'
end

desc 'Format'
task :format do
  sh 'rubocop -A || true'
end

desc 'Examples'
task :examples do
  sh 'ruby examples/enumerable.rb'
end