package com.example.constitution

/**
 * All learning content for the app, kept as plain data so the app stays simple
 * and offline. Mirrors the content of the companion web app.
 */

data class Fact(val label: String, val value: String)

data class Part(
    val part: String,
    val title: String,
    val articles: String,
    val summary: String,
)

data class Schedule(
    val schedule: String,
    val title: String,
    val detail: String,
)

data class Article(
    val number: String,
    val title: String,
    val part: String,
    val tags: List<String>,
    val text: String,
    val explanation: String,
)

data class Flashcard(val front: String, val back: String)

data class QuizQuestion(
    val question: String,
    val options: List<String>,
    val answer: Int,
    val explain: String,
)

object ConstitutionData {

    val facts = listOf(
        Fact("Adopted", "26 November 1949"),
        Fact("Came into force", "26 January 1950 (Republic Day)"),
        Fact("Articles (original)", "395 articles, 22 parts, 8 schedules"),
        Fact("Articles (current)", "~448 articles, 25 parts, 12 schedules"),
        Fact("Drafting Committee Chairman", "Dr. B. R. Ambedkar"),
        Fact("Constituent Assembly President", "Dr. Rajendra Prasad"),
        Fact("Time taken to draft", "2 years, 11 months, 18 days"),
        Fact("Nature", "Longest written constitution of any sovereign nation"),
    )

    val preamble = """
        WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC and to secure to all its citizens:
        JUSTICE, social, economic and political;
        LIBERTY of thought, expression, belief, faith and worship;
        EQUALITY of status and of opportunity;
        and to promote among them all
        FRATERNITY assuring the dignity of the individual and the unity and integrity of the Nation;
        IN OUR CONSTITUENT ASSEMBLY this twenty-sixth day of November, 1949, do HEREBY ADOPT, ENACT AND GIVE TO OURSELVES THIS CONSTITUTION.
    """.trimIndent()

    val preambleNotes = listOf(
        "The words 'SOCIALIST', 'SECULAR' and 'INTEGRITY' were added by the 42nd Amendment Act, 1976.",
        "The Preamble is based on the 'Objectives Resolution' moved by Jawaharlal Nehru.",
        "In Kesavananda Bharati (1973) and Berubari Union (1960), the Supreme Court clarified that the Preamble is part of the Constitution but is not enforceable in a court of law.",
        "It declares the source of authority of the Constitution to be the people of India.",
    )

    val parts = listOf(
        Part("Part I", "The Union and its Territory", "1-4", "Defines India as a 'Union of States', describes the territory of India, and gives Parliament the power to admit, establish or reorganise states and alter their boundaries."),
        Part("Part II", "Citizenship", "5-11", "Deals with citizenship at the commencement of the Constitution. The details of acquiring and losing citizenship are left to Parliament (Citizenship Act, 1955)."),
        Part("Part III", "Fundamental Rights", "12-35", "The 'Magna Carta' of India. Guarantees justiciable rights such as equality, freedom, protection against exploitation, freedom of religion, cultural & educational rights, and constitutional remedies."),
        Part("Part IV", "Directive Principles of State Policy", "36-51", "Non-justiciable guidelines for the State to establish a just social and economic order. Inspired by the Irish Constitution."),
        Part("Part IVA", "Fundamental Duties", "51A", "Added by the 42nd Amendment (1976). Lists the duties of every citizen. Originally 10, now 11 duties (the 11th added by the 86th Amendment, 2002)."),
        Part("Part V", "The Union (Central Government)", "52-151", "Covers the Executive (President, Vice-President, Council of Ministers, Attorney General), Parliament, the Union legislature, and the Supreme Court & CAG."),
        Part("Part VI", "The States", "152-237", "Covers the structure of state governments: Governor, Council of Ministers, State Legislature, and High Courts."),
        Part("Part VII", "(Repealed)", "—", "Originally dealt with Part B states. Repealed by the 7th Amendment Act, 1956."),
        Part("Part VIII", "The Union Territories", "239-242", "Administration of Union Territories, including provisions for a Lieutenant Governor and special arrangements for Delhi."),
        Part("Part IX", "The Panchayats", "243-243O", "Added by the 73rd Amendment (1992). Provides constitutional status to Panchayati Raj institutions (rural local self-government)."),
        Part("Part IXA", "The Municipalities", "243P-243ZG", "Added by the 74th Amendment (1992). Provides constitutional status to urban local bodies (Municipalities)."),
        Part("Part IXB", "The Co-operative Societies", "243ZH-243ZT", "Added by the 97th Amendment (2011). Deals with the incorporation, regulation and winding up of co-operative societies."),
        Part("Part X", "The Scheduled and Tribal Areas", "244-244A", "Provides for the administration of Scheduled Areas and Tribal Areas (Fifth and Sixth Schedules)."),
        Part("Part XI", "Relations between the Union and the States", "245-263", "Distributes legislative and administrative powers between the Centre and the States."),
        Part("Part XII", "Finance, Property, Contracts and Suits", "264-300A", "Deals with financial relations, distribution of taxes, the Finance Commission, and the right to property (Art 300A)."),
        Part("Part XIII", "Trade, Commerce and Intercourse", "301-307", "Guarantees freedom of trade, commerce and intercourse throughout the territory of India."),
        Part("Part XIV", "Services under the Union and the States", "308-323", "Covers public services and the Public Service Commissions (UPSC and SPSCs)."),
        Part("Part XIVA", "Tribunals", "323A-323B", "Added by the 42nd Amendment (1976). Provides for administrative tribunals and tribunals for other matters."),
        Part("Part XV", "Elections", "324-329A", "Provides for the Election Commission of India and the conduct of free and fair elections."),
        Part("Part XVI", "Special Provisions for Certain Classes", "330-342A", "Reservation of seats and special provisions for SCs, STs, Anglo-Indians (now lapsed) and backward classes."),
        Part("Part XVII", "Official Language", "343-351", "Declares Hindi in Devanagari script as the official language of the Union, with English continuing for official purposes."),
        Part("Part XVIII", "Emergency Provisions", "352-360", "Provides for three kinds of emergency: National (352), President's Rule in states (356), and Financial (360)."),
        Part("Part XIX", "Miscellaneous", "361-367", "Protection of the President and Governors, and other miscellaneous provisions."),
        Part("Part XX", "Amendment of the Constitution", "368", "Gives Parliament the power to amend the Constitution, subject to the 'basic structure' doctrine."),
        Part("Part XXI", "Temporary, Transitional and Special Provisions", "369-392", "Includes special provisions for certain states (e.g., the now-abrogated Article 370 for Jammu & Kashmir)."),
        Part("Part XXII", "Short Title, Commencement, Authoritative Text & Repeals", "393-395", "Final provisions: short title, date of commencement, authoritative Hindi text, and repeals."),
    )

    val schedules = listOf(
        Schedule("First Schedule", "States and Union Territories", "Lists the States and Union Territories of India and their territories."),
        Schedule("Second Schedule", "Salaries & Emoluments", "Provisions on the salaries, allowances and privileges of the President, Governors, judges, the CAG, etc."),
        Schedule("Third Schedule", "Forms of Oaths and Affirmations", "Forms of oaths/affirmations for ministers, MPs/MLAs, judges and the CAG."),
        Schedule("Fourth Schedule", "Allocation of Rajya Sabha Seats", "Allocates seats in the Rajya Sabha (Council of States) to states and union territories."),
        Schedule("Fifth Schedule", "Administration of Scheduled Areas", "Administration and control of Scheduled Areas and Scheduled Tribes."),
        Schedule("Sixth Schedule", "Tribal Areas", "Administration of tribal areas in Assam, Meghalaya, Tripura and Mizoram via Autonomous District Councils."),
        Schedule("Seventh Schedule", "Union, State & Concurrent Lists", "Divides legislative powers between the Union and the States through three lists."),
        Schedule("Eighth Schedule", "Languages", "Lists the 22 official languages recognised by the Constitution."),
        Schedule("Ninth Schedule", "Validation of Certain Acts", "Added by the 1st Amendment (1951) to protect land-reform laws from judicial review (now reviewable for basic structure violations)."),
        Schedule("Tenth Schedule", "Anti-Defection Law", "Added by the 52nd Amendment (1985). Provides for disqualification of members on grounds of defection."),
        Schedule("Eleventh Schedule", "Powers of Panchayats", "Added by the 73rd Amendment (1992). Lists 29 functional subjects of Panchayats."),
        Schedule("Twelfth Schedule", "Powers of Municipalities", "Added by the 74th Amendment (1992). Lists 18 functional subjects of Municipalities."),
    )

    val articles = listOf(
        Article("Article 1", "Name and territory of the Union", "Part I", listOf("Union", "Territory"),
            "India, that is Bharat, shall be a Union of States. The territory of India comprises the territories of the States, the Union Territories, and any other territories that may be acquired.",
            "Article 1 describes India as a 'Union of States' rather than a 'Federation of States'. Dr. Ambedkar explained that the word 'Union' was deliberately chosen to convey two ideas: (1) the Indian federation is not the result of an agreement among states, and (2) no state has the right to secede from the Union. India is thus an indestructible union of destructible states — Parliament can reorganise states, but states cannot leave the Union."),
        Article("Article 3", "Formation of new States and alteration of areas", "Part I", listOf("Reorganisation"),
            "Parliament may by law form a new State, increase or diminish the area of any State, or alter the boundaries or name of any State.",
            "This article gives Parliament wide power to redraw the political map of India by a simple majority. The President must refer the bill to the affected state legislature for its views, but Parliament is not bound by those views. This power has been used many times — e.g., the States Reorganisation Act of 1956 and the creation of states like Telangana (2014)."),
        Article("Article 12", "Definition of 'State'", "Part III", listOf("Fundamental Rights"),
            "In Part III, unless the context otherwise requires, 'the State' includes the Government and Parliament of India, the Government and Legislature of each State, and all local or other authorities within the territory of India or under the control of the Government of India.",
            "Article 12 defines the term 'State' for the purpose of Fundamental Rights, because most rights in Part III are enforceable against the State. Courts have interpreted 'other authorities' broadly to include statutory bodies, government companies and any body that is an 'instrumentality or agency of the State'."),
        Article("Article 13", "Laws inconsistent with Fundamental Rights", "Part III", listOf("Fundamental Rights", "Judicial Review"),
            "All laws in force that are inconsistent with the Fundamental Rights are void to the extent of inconsistency. The State shall not make any law that takes away or abridges these rights.",
            "Article 13 is the constitutional basis for the power of judicial review in matters of Fundamental Rights. It declares that any law violating Part III is void. It applies the doctrines of severability (only the offending portion is struck down) and eclipse (a pre-Constitution law becomes dormant rather than dead)."),
        Article("Article 14", "Equality before law", "Part III", listOf("Equality", "Fundamental Rights"),
            "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
            "Article 14 guarantees two things: 'equality before law' (a British concept implying the absence of special privileges) and 'equal protection of the laws' (an American concept implying equal treatment in equal circumstances). It permits 'reasonable classification' — the State may treat different groups differently if the classification is based on an intelligible differentia having a rational nexus with the objective. It forbids arbitrariness in State action."),
        Article("Article 15", "Prohibition of discrimination", "Part III", listOf("Equality", "Fundamental Rights"),
            "The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex or place of birth.",
            "Article 15 prohibits discrimination on five specific grounds. It includes enabling provisions allowing the State to make special provisions for women, children, socially and educationally backward classes, SCs and STs (including reservations in educational institutions under Article 15(5))."),
        Article("Article 16", "Equality of opportunity in public employment", "Part III", listOf("Equality", "Reservation"),
            "There shall be equality of opportunity for all citizens in matters of public employment. The State may make provision for the reservation of appointments for backward classes not adequately represented.",
            "Article 16 guarantees equal opportunity in government jobs while permitting reservations for backward classes, SCs and STs. The landmark Indra Sawhney case (1992) upheld reservations but capped them at 50% (subject to exceptions) and introduced the 'creamy layer' exclusion."),
        Article("Article 17", "Abolition of Untouchability", "Part III", listOf("Equality"),
            "'Untouchability' is abolished and its practice in any form is forbidden. Enforcing any disability arising out of 'untouchability' is an offence punishable by law.",
            "Article 17 abolishes untouchability — one of the few rights enforceable against private individuals, not just the State. It is given effect through the Protection of Civil Rights Act, 1955 and the SC/ST (Prevention of Atrocities) Act, 1989."),
        Article("Article 19", "Six Freedoms", "Part III", listOf("Freedom", "Fundamental Rights"),
            "All citizens have the right to (a) freedom of speech and expression; (b) assemble peaceably and without arms; (c) form associations or unions; (d) move freely throughout India; (e) reside and settle in any part of India; (g) practise any profession, or carry on any occupation, trade or business.",
            "Article 19 guarantees six fundamental freedoms to citizens. Each freedom can be restricted only by 'reasonable restrictions' on specific grounds listed in the article (e.g., security of the State, public order, decency, morality). The original right to property under 19(1)(f) was removed by the 44th Amendment (1978)."),
        Article("Article 21", "Protection of life and personal liberty", "Part III", listOf("Life", "Liberty", "Fundamental Rights"),
            "No person shall be deprived of his life or personal liberty except according to procedure established by law.",
            "Article 21 is the heart of fundamental rights. After Maneka Gandhi v. Union of India (1978), the procedure must be 'just, fair and reasonable', not arbitrary. The Supreme Court has expanded Article 21 to include the right to privacy (Puttaswamy, 2017), the right to a clean environment, livelihood, health, shelter, dignity, speedy trial and education."),
        Article("Article 21A", "Right to Education", "Part III", listOf("Education", "Fundamental Rights"),
            "The State shall provide free and compulsory education to all children of the age of six to fourteen years in such manner as the State may determine.",
            "Article 21A was inserted by the 86th Amendment Act, 2002, making elementary education a fundamental right. It is implemented through the Right of Children to Free and Compulsory Education (RTE) Act, 2009."),
        Article("Article 22", "Protection against arrest and detention", "Part III", listOf("Liberty", "Fundamental Rights"),
            "Provides safeguards against arbitrary arrest and detention, including the right to be informed of grounds of arrest, to consult a lawyer, and to be produced before a magistrate within 24 hours.",
            "Article 22 has two parts: protections for ordinary arrests, and a separate set of (weaker) safeguards for preventive detention. Preventive detention allows detention without trial to prevent future offences, subject to review by an Advisory Board."),
        Article("Article 23", "Prohibition of trafficking and forced labour", "Part III", listOf("Exploitation", "Fundamental Rights"),
            "Traffic in human beings, begar (forced labour) and other similar forms of forced labour are prohibited and any contravention is an offence.",
            "Article 23 protects against human trafficking and forced labour. It is enforceable against both the State and private persons. The State may impose compulsory service for public purposes (e.g., military service) without discrimination."),
        Article("Article 24", "Prohibition of child labour", "Part III", listOf("Exploitation", "Children"),
            "No child below the age of fourteen years shall be employed in any factory or mine or engaged in any other hazardous employment.",
            "Article 24 prohibits the employment of children below 14 in factories, mines and hazardous work. It is supported by laws such as the Child Labour (Prohibition and Regulation) Act, 1986."),
        Article("Article 25", "Freedom of religion", "Part III", listOf("Religion", "Fundamental Rights"),
            "All persons are equally entitled to freedom of conscience and the right freely to profess, practise and propagate religion, subject to public order, morality and health.",
            "Article 25 guarantees freedom of conscience and religion to all persons (not just citizens). It is subject to public order, morality, health and other fundamental rights. The State can regulate secular activities associated with religion and provide for social welfare and reform."),
        Article("Article 32", "Right to Constitutional Remedies", "Part III", listOf("Remedies", "Writs", "Fundamental Rights"),
            "The right to move the Supreme Court for the enforcement of Fundamental Rights is guaranteed. The Supreme Court may issue writs — habeas corpus, mandamus, prohibition, certiorari and quo warranto.",
            "Dr. Ambedkar called Article 32 'the heart and soul of the Constitution' because it makes Fundamental Rights meaningful by guaranteeing a remedy. It is itself a Fundamental Right. The five writs are powerful tools to protect citizens against unlawful State action. (High Courts have similar power under Article 226, which is wider.)"),
        Article("Article 36-51", "Directive Principles of State Policy", "Part IV", listOf("DPSP"),
            "Directives to the State to secure a social order based on justice, adequate means of livelihood, equal pay for equal work, free legal aid, organisation of village panchayats, the right to work, a uniform civil code, protection of the environment and promotion of international peace.",
            "Part IV (Articles 36-51) contains the Directive Principles — non-justiciable goals borrowed from the Irish Constitution. Though not enforceable in court, they are 'fundamental in the governance of the country'. They are classified as Socialistic (e.g., Art 39, 41, 43), Gandhian (e.g., Art 40, 43, 46) and Liberal-Intellectual (e.g., Art 44, 48, 51) principles."),
        Article("Article 40", "Organisation of village panchayats", "Part IV", listOf("DPSP", "Gandhian"),
            "The State shall take steps to organise village panchayats and endow them with such powers and authority as may be necessary to enable them to function as units of self-government.",
            "A Gandhian Directive Principle reflecting the ideal of Gram Swaraj (village self-rule). It was given concrete shape decades later through the 73rd Amendment Act, 1992."),
        Article("Article 44", "Uniform Civil Code", "Part IV", listOf("DPSP"),
            "The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.",
            "Article 44 expresses the goal of a common set of personal laws (marriage, divorce, inheritance) for all citizens regardless of religion. It remains a directive principle and a subject of ongoing public debate."),
        Article("Article 50", "Separation of judiciary from executive", "Part IV", listOf("DPSP"),
            "The State shall take steps to separate the judiciary from the executive in the public services of the State.",
            "This principle aims to ensure an independent judiciary by separating judicial functions from executive control, a goal largely achieved through the Code of Criminal Procedure, 1973."),
        Article("Article 51A", "Fundamental Duties", "Part IVA", listOf("Duties"),
            "Lists the eleven fundamental duties of every citizen, including to abide by the Constitution, cherish the freedom struggle, protect sovereignty, promote harmony, preserve the environment, develop scientific temper, and provide opportunities for education to one's child (the 11th duty).",
            "Fundamental Duties were added by the 42nd Amendment (1976) on the recommendation of the Swaran Singh Committee, inspired by the Soviet Constitution. Originally ten, the 86th Amendment (2002) added the duty of every parent/guardian to provide education to children aged 6-14. Duties are not legally enforceable but serve as a constant reminder of civic responsibility."),
        Article("Article 52-53", "The President of India", "Part V", listOf("Executive", "President"),
            "There shall be a President of India in whom the executive power of the Union is vested and exercised by him directly or through officers subordinate to him in accordance with the Constitution.",
            "The President is the constitutional head of the Union executive. Real executive power is exercised by the Council of Ministers headed by the Prime Minister (Article 74), whose advice is binding on the President (after the 42nd and 44th Amendments). The President is elected indirectly by an electoral college (Article 54)."),
        Article("Article 72", "Pardoning power of the President", "Part V", listOf("Executive", "President"),
            "The President has the power to grant pardons, reprieves, respites or remissions of punishment, or to suspend, remit or commute a sentence, in certain cases including all death sentences.",
            "Article 72 gives the President clemency powers, which act as a check against possible judicial errors and as an instrument of mercy. Governors have a similar but narrower power under Article 161 (Governors cannot pardon a death sentence or punishments by court-martial)."),
        Article("Article 74-75", "Council of Ministers and Prime Minister", "Part V", listOf("Executive"),
            "There shall be a Council of Ministers headed by the Prime Minister to aid and advise the President, who shall act in accordance with such advice. The Prime Minister is appointed by the President; other ministers are appointed on the PM's advice.",
            "Articles 74 and 75 establish the parliamentary system of government in India. The Council of Ministers is collectively responsible to the Lok Sabha (Article 75(3)). The 91st Amendment (2003) capped the size of the Council of Ministers at 15% of the strength of the Lok Sabha."),
        Article("Article 79-100", "Parliament", "Part V", listOf("Legislature"),
            "Parliament consists of the President, the Council of States (Rajya Sabha) and the House of the People (Lok Sabha). These articles cover its composition, sessions, officers, and the conduct of business.",
            "India has a bicameral Parliament. The Lok Sabha (lower house) is directly elected and is the more powerful house, especially in money matters. The Rajya Sabha (upper house) represents the states and is a permanent body that is never fully dissolved (one-third of members retire every two years)."),
        Article("Article 110", "Money Bills", "Part V", listOf("Legislature", "Finance"),
            "Defines a Money Bill as one dealing only with matters such as taxation, government borrowing, and the Consolidated Fund of India. The Speaker of the Lok Sabha certifies whether a bill is a Money Bill.",
            "Money Bills can be introduced only in the Lok Sabha and only on the President's recommendation. The Rajya Sabha can only suggest changes within 14 days but cannot reject a Money Bill, giving the Lok Sabha decisive control over finances."),
        Article("Article 124", "Establishment of the Supreme Court", "Part V", listOf("Judiciary"),
            "There shall be a Supreme Court of India consisting of a Chief Justice and other judges. Judges are appointed by the President and hold office until the age of 65.",
            "Article 124 establishes the Supreme Court as the apex court and guardian of the Constitution. Judicial independence is protected through security of tenure, fixed salaries charged on the Consolidated Fund, and a difficult removal process (impeachment for 'proved misbehaviour or incapacity')."),
        Article("Article 143", "Advisory jurisdiction of the Supreme Court", "Part V", listOf("Judiciary"),
            "The President may refer a question of law or fact of public importance to the Supreme Court for its opinion.",
            "Article 143 gives the Supreme Court advisory (consultative) jurisdiction. The opinion is not binding on the President and is not a judgment, but it carries great persuasive value. It has been used in cases like the Berubari and Ayodhya references."),
        Article("Article 148", "Comptroller and Auditor-General (CAG)", "Part V", listOf("Audit"),
            "There shall be a Comptroller and Auditor-General of India who audits the accounts of the Union and the States and reports to the legislatures.",
            "The CAG is the guardian of the public purse and one of the bulwarks of the democratic system. Dr. Ambedkar described the CAG as one of the most important officers under the Constitution. The CAG's reports are examined by the Public Accounts Committee."),
        Article("Article 153-162", "The Governor of a State", "Part VI", listOf("Executive", "States"),
            "There shall be a Governor for each State who is the constitutional head of the State executive, appointed by the President and holding office during the President's pleasure.",
            "The Governor is the state counterpart of the President. The Governor acts on the advice of the State Council of Ministers but also has certain discretionary powers (e.g., reserving bills for the President, reporting on the failure of constitutional machinery)."),
        Article("Article 226", "Power of High Courts to issue writs", "Part VI", listOf("Judiciary", "Writs"),
            "Every High Court has the power to issue writs for the enforcement of Fundamental Rights and for any other purpose.",
            "Article 226 gives High Courts a wider writ jurisdiction than the Supreme Court under Article 32, because High Courts can issue writs not only for Fundamental Rights but for 'any other purpose' (i.e., ordinary legal rights too). Unlike Article 32, the right to approach a High Court is not itself a Fundamental Right."),
        Article("Article 243", "Panchayati Raj", "Part IX", listOf("Local Government"),
            "Provides for a three-tier system of Panchayats at the village, intermediate and district levels, with regular elections, reservation of seats, and a State Finance Commission.",
            "Part IX, added by the 73rd Amendment (1992), gave constitutional status to rural local self-government. It mandates elections every five years, reservation for SCs, STs and women (at least one-third), and the establishment of State Election Commissions and State Finance Commissions."),
        Article("Article 280", "Finance Commission", "Part XII", listOf("Finance"),
            "The President shall constitute a Finance Commission every five years to recommend the distribution of tax revenues between the Union and the States.",
            "The Finance Commission is a quasi-judicial body that addresses vertical and horizontal fiscal imbalances by recommending how taxes should be shared between the Centre and the States and among the States themselves."),
        Article("Article 300A", "Right to Property", "Part XII", listOf("Property"),
            "No person shall be deprived of his property save by authority of law.",
            "Originally a Fundamental Right (Articles 19(1)(f) and 31), the right to property was removed from Part III by the 44th Amendment (1978) and made a constitutional/legal right under Article 300A. The State can now acquire property by law, but the action must still be lawful and non-arbitrary."),
        Article("Article 324", "Election Commission of India", "Part XV", listOf("Elections"),
            "The superintendence, direction and control of elections to Parliament, State Legislatures, and the offices of President and Vice-President shall vest in an Election Commission.",
            "Article 324 establishes the Election Commission of India (ECI) as an independent constitutional body responsible for conducting free and fair elections. It is currently a multi-member body (Chief Election Commissioner and Election Commissioners)."),
        Article("Article 352", "National Emergency", "Part XVIII", listOf("Emergency"),
            "If the President is satisfied that the security of India is threatened by war, external aggression or armed rebellion, a Proclamation of National Emergency may be made.",
            "A National Emergency under Article 352 can be declared on grounds of war, external aggression, or armed rebellion (the term 'internal disturbance' was replaced by 'armed rebellion' by the 44th Amendment, 1978). It must be approved by both Houses within one month. The most controversial use was the 1975-77 Emergency."),
        Article("Article 356", "President's Rule (State Emergency)", "Part XVIII", listOf("Emergency"),
            "If the President is satisfied that the government of a State cannot be carried on in accordance with the Constitution, the President may assume the functions of the State government.",
            "Article 356 imposes 'President's Rule' when constitutional machinery fails in a state. The landmark S. R. Bommai case (1994) laid down strict guidelines to curb its misuse, including that the floor of the Assembly is the proper place to test a government's majority and that the proclamation is subject to judicial review."),
        Article("Article 360", "Financial Emergency", "Part XVIII", listOf("Emergency"),
            "If the President is satisfied that the financial stability or credit of India is threatened, a Proclamation of Financial Emergency may be made.",
            "Article 360 allows the Centre to direct states to observe financial propriety and reduce salaries, including those of judges. A Financial Emergency has never been declared in India to date."),
        Article("Article 368", "Amendment of the Constitution", "Part XX", listOf("Amendment", "Basic Structure"),
            "Parliament may amend the Constitution by way of addition, variation or repeal, following the prescribed procedure. Some amendments require a special majority; others also require ratification by half the state legislatures.",
            "Article 368 provides the amendment procedure. The Kesavananda Bharati case (1973) established the 'Basic Structure Doctrine': Parliament can amend any part of the Constitution but cannot alter its basic structure (e.g., supremacy of the Constitution, rule of law, separation of powers, federalism, secularism, judicial review and free elections)."),
        Article("Article 370", "Special status for Jammu & Kashmir (abrogated)", "Part XXI", listOf("Special Provisions"),
            "A 'temporary provision' that granted special autonomous status to the State of Jammu and Kashmir.",
            "Article 370 gave Jammu & Kashmir a separate constitution and significant autonomy. In August 2019, the Government effectively abrogated its special status, and the state was reorganised into two Union Territories. The Supreme Court upheld the abrogation in December 2023."),
    )

    val flashcards = listOf(
        Flashcard("When did the Constitution of India come into force?", "26 January 1950, celebrated as Republic Day. It was adopted earlier on 26 November 1949 (Constitution Day)."),
        Flashcard("Who was the Chairman of the Drafting Committee?", "Dr. B. R. Ambedkar, often called the chief architect of the Indian Constitution."),
        Flashcard("Which Part contains the Fundamental Rights?", "Part III (Articles 12-35)."),
        Flashcard("Which Article is called the 'heart and soul' of the Constitution?", "Article 32 — the Right to Constitutional Remedies (Dr. Ambedkar's words)."),
        Flashcard("What are the five writs under Article 32?", "Habeas Corpus, Mandamus, Prohibition, Certiorari and Quo Warranto."),
        Flashcard("Which Amendment added the words SOCIALIST, SECULAR and INTEGRITY to the Preamble?", "The 42nd Amendment Act, 1976."),
        Flashcard("Which Article guarantees the Right to Education?", "Article 21A, inserted by the 86th Amendment Act, 2002 (free and compulsory education for ages 6-14)."),
        Flashcard("From which country was the idea of Directive Principles borrowed?", "Ireland (the Irish Constitution)."),
        Flashcard("What is the Basic Structure Doctrine?", "Established in Kesavananda Bharati (1973): Parliament can amend the Constitution but cannot destroy its basic structure."),
        Flashcard("How many Fundamental Duties are there now?", "Eleven. Originally ten (42nd Amendment, 1976); the 11th was added by the 86th Amendment, 2002."),
        Flashcard("Which Article deals with the abolition of untouchability?", "Article 17."),
        Flashcard("Which two amendments gave constitutional status to local self-government?", "73rd Amendment (Panchayats) and 74th Amendment (Municipalities), both in 1992."),
        Flashcard("What are the three types of emergencies in the Constitution?", "National Emergency (Art 352), President's Rule / State Emergency (Art 356), and Financial Emergency (Art 360)."),
        Flashcard("How many Schedules does the Constitution currently have?", "Twelve schedules (originally eight)."),
        Flashcard("Which Article was used to abrogate the special status of Jammu & Kashmir?", "Article 370 (effectively abrogated in August 2019)."),
        Flashcard("Who was the President of the Constituent Assembly?", "Dr. Rajendra Prasad."),
        Flashcard("What does Article 14 guarantee?", "Equality before the law and equal protection of the laws."),
        Flashcard("Which case expanded the meaning of 'right to life' under Article 21?", "Maneka Gandhi v. Union of India (1978) — procedure must be just, fair and reasonable."),
        Flashcard("Which Schedule contains the anti-defection law?", "The Tenth Schedule (added by the 52nd Amendment, 1985)."),
        Flashcard("Which body recommends the sharing of taxes between the Centre and States?", "The Finance Commission, constituted under Article 280."),
    )

    val quiz = listOf(
        QuizQuestion("On which date did the Constitution of India come into effect?",
            listOf("15 August 1947", "26 November 1949", "26 January 1950", "2 October 1950"), 2,
            "It came into force on 26 January 1950, celebrated as Republic Day. It was adopted on 26 November 1949."),
        QuizQuestion("Who is regarded as the chief architect of the Indian Constitution?",
            listOf("Jawaharlal Nehru", "Dr. B. R. Ambedkar", "Sardar Vallabhbhai Patel", "Dr. Rajendra Prasad"), 1,
            "Dr. B. R. Ambedkar chaired the Drafting Committee and is the chief architect of the Constitution."),
        QuizQuestion("Fundamental Rights are contained in which Part of the Constitution?",
            listOf("Part II", "Part III", "Part IV", "Part V"), 1,
            "Part III (Articles 12-35) contains the Fundamental Rights."),
        QuizQuestion("Which Article is known as the 'heart and soul' of the Constitution?",
            listOf("Article 14", "Article 19", "Article 21", "Article 32"), 3,
            "Dr. Ambedkar called Article 32 (Right to Constitutional Remedies) the heart and soul of the Constitution."),
        QuizQuestion("The Directive Principles of State Policy were borrowed from the Constitution of which country?",
            listOf("United States", "United Kingdom", "Ireland", "Canada"), 2,
            "The concept of Directive Principles was borrowed from the Irish Constitution."),
        QuizQuestion("Which amendment added the words 'Socialist' and 'Secular' to the Preamble?",
            listOf("1st Amendment", "42nd Amendment", "44th Amendment", "73rd Amendment"), 1,
            "The 42nd Amendment (1976) added 'Socialist', 'Secular' and 'Integrity' to the Preamble."),
        QuizQuestion("The Basic Structure Doctrine was laid down in which landmark case?",
            listOf("Maneka Gandhi case", "Kesavananda Bharati case", "Golaknath case", "Minerva Mills case"), 1,
            "Kesavananda Bharati v. State of Kerala (1973) established the Basic Structure Doctrine."),
        QuizQuestion("How many Fundamental Duties are currently listed in the Constitution?",
            listOf("10", "11", "12", "9"), 1,
            "There are 11 Fundamental Duties (Article 51A); the 11th was added by the 86th Amendment in 2002."),
        QuizQuestion("Article 21A guarantees which right?",
            listOf("Right to Property", "Right to Education", "Right to Privacy", "Right to Information"), 1,
            "Article 21A provides the Right to Education for children aged 6 to 14 years."),
        QuizQuestion("Which Article provides for President's Rule in a State?",
            listOf("Article 352", "Article 356", "Article 360", "Article 370"), 1,
            "Article 356 deals with President's Rule (State Emergency) when constitutional machinery fails."),
        QuizQuestion("The 73rd Amendment Act of 1992 is associated with which institution?",
            listOf("Municipalities", "Panchayati Raj", "Co-operative Societies", "Tribunals"), 1,
            "The 73rd Amendment gave constitutional status to Panchayati Raj (rural local government)."),
        QuizQuestion("Which writ literally means 'to have the body'?",
            listOf("Mandamus", "Certiorari", "Habeas Corpus", "Quo Warranto"), 2,
            "Habeas Corpus means 'to have the body' and is used against unlawful detention."),
        QuizQuestion("How many Schedules does the Constitution currently contain?",
            listOf("8", "10", "12", "14"), 2,
            "There are 12 Schedules currently (originally 8)."),
        QuizQuestion("The right to property is now protected under which Article?",
            listOf("Article 19(1)(f)", "Article 31", "Article 300A", "Article 21"), 2,
            "After the 44th Amendment (1978), the right to property became a legal right under Article 300A."),
        QuizQuestion("Which body conducts elections to Parliament and State Legislatures?",
            listOf("Finance Commission", "Election Commission of India", "UPSC", "NITI Aayog"), 1,
            "Article 324 vests the conduct of elections in the Election Commission of India."),
    )
}
